[build]
  command = "npm run build"
  publish = "_site"

# ✅ Redirect /admin and all subroutes to the CMS entry point
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200


# ✅ Optional: redirect /login or /reset-password to /admin for UX clarity
[[redirects]]
  from = "/login"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/reset-password"
  to = "/admin/index.html"
  status = 200