backend:
  name: git-gateway
  branch: main

media_folder: "src/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "packages"
    label: "Travel Packages"
    folder: "src/packages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Destination", name: "destination", widget: "string" }
      - { label: "Price", name: "price", widget: "string", required: false }
      - { label: "Duration", name: "duration", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }