backend:
  name: github
  repo: yourtripndeal/tripndeal-site
  branch: main
  auth_scope: repo
  base_url: https://yourtripndeal.auth0.com
  client_id: 9xWvKfT2gH3J7bQvL8mX9zPqR5dT6cN1

local_backend: true

site_url: https://tripndeal.com
logo_url: /images/logo.png

media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "about"
    label: "About Us"
    files:
      - file: "src/about.njk"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Intro", name: "intro", widget: "text" }
          - { label: "Mission", name: "mission", widget: "text" }
          - { label: "Why Choose Us", name: "why", widget: "list", field: { label: "Point", name: "point", widget: "string" } }

  - name: "packages"
    label: "Travel Packages"
    folder: "src/packages"
    create: true
    slug: "{{slug}}"
    preview_path: "packages/{{slug}}"
    summary: "{{title}} — {{description}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }