backend:
  name: git-gateway
  repo: yourtripndeal/tripndeal-site
  branch: main
  auth_scope: repo
  base_url: "${AUTH0_DOMAIN}"
  client_id: "${AUTH0_CLIENT_ID}"

media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "about"
    label: "About Us"
    files:
      - file: "src/about.njk"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Intro", name: "intro", widget: "text" }
          - { label: "Mission", name: "mission", widget: "text" }
          - { label: "Why Choose Us", name: "why", widget: "list", field: { label: "Point", name: "point", widget: "string" } }

  - name: "packages"
    label: "Travel Packages"
    folder: "src/packages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
